"""
music/now_playing.py

Now Playing embed + interactive button controls for BandiBot.

Posts a visual playback display in the text channel when a song starts.
The banner image is generated by banner.py and attached to a Discord embed
whose footer shows a live playback timer, queue size, and next track.

State machine:
  Playing    → banner image + live timer footer + active button row
  New track  → banner regenerated, embed reposted or edited in place
  Queue empty → now playing message deleted, plain queue-finished embed posted

Transition behavior:
  Natural transition (song ends normally) → delete old embed, repost new one
  Manual transition (skip, restart)       → edit existing embed in place

Button rows:
  Row 0: ⏮ Previous | ▶/⏸ Play/Pause | ⏭ Skip | ⏹ Stop
  Row 1: 📋 Queue   | 🔁 Loop        | 🔀 Shuffle | 🔗 Copy Link

Timer loop updates the footer every 10 seconds with elapsed/total duration.
Queue finished messages are cleaned up when a new song starts playing.
"""

import asyncio
import io
import logging
from typing import Optional

import discord

from music.banner import generate_banner
from music.player import voice_manager

logger = logging.getLogger(__name__)

EMBED_COLOR = 0x4A148C
EMPTY_COLOR = 0x2C2C3A  # dimmer color for the queue-empty state
TIMER_INTERVAL = 10     # seconds between footer timer edits


def _format_duration(seconds) -> str:
    """Format seconds as M:SS or H:MM:SS. Returns '—:—' if unknown."""
    if seconds is None or seconds <= 0:
        return "—:—"
    hours, remainder = divmod(int(seconds), 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"

def _estimate_width(text: str) -> float:
    """Estimate rendered width of text using character-width approximations."""
    narrow = set('iIl1|!.,;: ')
    wide   = set('WMmwW@')
    total  = 0.0
    for ch in text:
        if ch in narrow:
            total += 0.5
        elif ch in wide:
            total += 1.3
        else:
            total += 1.0
    return total

NEXT_TRACK_MAX_WIDTH = 28.0  # tweak this to calibrate

def _fit_next_track(title: str) -> str:
    """Truncate title to fit within pixel-width budget, appending … if needed."""
    if _estimate_width(title) <= NEXT_TRACK_MAX_WIDTH:
        return title
    truncated = ""
    for ch in title:
        candidate = truncated + ch
        if _estimate_width(candidate + "…") > NEXT_TRACK_MAX_WIDTH:
            return truncated + "…"
        truncated = candidate
    return truncated

def _build_playing_embed(
    queue_size: int,
    requested_by: str,
    duration_str: str = "0:00 / —:—",
    next_track: Optional[str] = None,
) -> discord.Embed:
    embed = discord.Embed(color=EMBED_COLOR)
    embed.set_author(name="✦  Now Playing")
    embed.set_image(url="attachment://now_playing.png")
    next_line = f"\n⏭ Up next: {_fit_next_track(next_track)}" if next_track else ""
    embed.set_footer(
        text=f"⏱ {duration_str}                                 🎵 {queue_size} in queue{next_line}\n👤 Requested by {requested_by}"
    )
    return embed


def _build_empty_embed() -> discord.Embed:
    """Build the embed for the queue-empty state."""
    embed = discord.Embed(
        description="## Queue finished\nAdd more songs by mentioning me.",
        color=EMPTY_COLOR,
    )
    embed.set_author(name="✦  BandiBot")
    return embed


class NowPlayingView(discord.ui.View):
    """The button row attached to a Now Playing embed.

    Owns the timer update task and handles state transitions when songs
    change or the queue empties.

    Row 0: ⏮ Previous | ▶/⏸ Play/Pause | ⏭ Skip | ⏹ Stop
    Row 1: 📋 Queue    | 🔁 Loop        | 🔀 Shuffle | 🔗 Copy Link
    """

    def __init__(self, guild: discord.Guild, player):
        super().__init__(timeout=None)
        self.guild = guild
        self.player = player
        self.message: Optional[discord.Message] = None
        self._timer_task: Optional[asyncio.Task] = None

    def start_updates(self):
        if self._timer_task:
            self._timer_task.cancel()
        self._timer_task = asyncio.create_task(self._timer_loop())

    async def stop_updates(self):
        if self._timer_task:
            self._timer_task.cancel()
            self._timer_task = None

    async def _timer_loop(self):
        try:
            while True:
                await asyncio.sleep(TIMER_INTERVAL)
                if not self.message:
                    break
                track = self.player.current
                if not track:
                    break
                if track.paused_at is not None:
                    continue

                elapsed = self.player.elapsed_seconds
                duration_str = f"{_format_duration(int(elapsed))} / {_format_duration(track.duration)}"
                next_track = self.player.queue[0].title if self.player.queue else None

                try:
                    embed = _build_playing_embed(
                        queue_size=len(self.player.queue),
                        requested_by=track.requested_by,
                        duration_str=duration_str,
                        next_track=next_track,
                    )
                    await self.message.edit(embed=embed)
                except discord.NotFound:
                    self.message = None
                    break
                except Exception as e:
                    logger.error(f"[now_playing] timer update failed: {e}")
        except asyncio.CancelledError:
            pass

    async def on_track_changed(self, track, queue_size: int):
        """New track started — delete and repost if natural transition, edit in place if manual."""
        # Delete any lingering queue finished messages
        if self.player.queue_empty_message:
            try:
                await self.player.queue_empty_message.delete()
            except Exception:
                pass
            self.player.queue_empty_message = None

        natural = self.player._natural_transition
        self.player._natural_transition = False

        self.pause_resume_button.emoji = discord.PartialEmoji.from_str("<:pause:1501401053277454416>")

        try:
            png_bytes = await generate_banner(
                track.title, track.artist, track.thumbnail, track.thumbnail_bytes
            )
        except Exception as e:
            logger.error(f"[now_playing] banner regen failed: {e}")
            return

        duration_str = f"0:00 / {_format_duration(track.duration)}"
        next_track = self.player.queue[0].title if self.player.queue else None
        embed = _build_playing_embed(
            queue_size=queue_size,
            requested_by=track.requested_by,
            duration_str=duration_str,
            next_track=next_track,
        )
        file = discord.File(fp=io.BytesIO(png_bytes), filename="now_playing.png")

        if natural and self.message:
            channel = self.message.channel
            try:
                await self.message.delete()
            except Exception:
                pass
            self.message = None
            try:
                self.message = await channel.send(file=file, embed=embed, view=self)
            except Exception as e:
                logger.error(f"[now_playing] repost failed: {e}")
                return
        else:
            if not self.message:
                if not self.player.text_channel:
                    return
                try:
                    self.message = await self.player.text_channel.send(file=file, embed=embed, view=self)
                except Exception as e:
                    logger.error(f"[now_playing] fresh post failed: {e}")
                    return
            else:
                try:
                    await self.message.edit(attachments=[file], embed=embed, view=self)
                except Exception as e:
                    logger.error(f"[now_playing] track change edit failed: {e}")
                    return

        self.start_updates()

    async def on_queue_empty(self):
        """Queue exhausted — delete the now playing message and post a plain queue-finished embed."""
        await self.stop_updates()

        if not self.message:
            return

        channel = self.message.channel
        try:
            await self.message.delete()
        except Exception:
            pass
        self.message = None

        try:
            msg = await channel.send(embed=_build_empty_embed())
            self.player.queue_empty_message = msg
        except Exception as e:
            logger.error(f"[now_playing] queue empty post failed: {e}")

    # ── Row 0: playback controls ──────────────────────────────────────────────

    @discord.ui.button(emoji="<:previous:1501401326414987335>", style=discord.ButtonStyle.secondary, row=0)  # ⏮ Previous
    async def previous_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        await voice_manager.restart(self.guild)
        await interaction.response.defer()

    @discord.ui.button(emoji="<:pause:1501401053277454416>", style=discord.ButtonStyle.secondary, row=0)  # ▶/⏸ Play / Pause
    async def pause_resume_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        player = voice_manager.get_player(self.guild)
        if not player.is_connected:
            await interaction.response.defer()
            return
        if player.voice_client.is_paused():
            await voice_manager.resume(self.guild)
            button.emoji = discord.PartialEmoji.from_str("<:pause:1501401053277454416>")
        else:
            await voice_manager.pause(self.guild)
            button.emoji = discord.PartialEmoji.from_str("<:play:1501399530170482768>")
        await interaction.response.edit_message(view=self)

    @discord.ui.button(emoji="<:skip:1501400932641013962>", style=discord.ButtonStyle.secondary, row=0)  # ⏭ Skip
    async def skip_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        await voice_manager.skip(self.guild)
        await interaction.response.defer()

    @discord.ui.button(emoji="<:stop:1501401472259067924>", style=discord.ButtonStyle.danger, row=0)  # ⏹ Stop
    async def stop_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        await self.stop_updates()
        if self.message:
            try:
                await self.message.delete()
            except Exception:
                pass
            self.message = None
        await voice_manager.stop(self.guild)
        await interaction.response.defer()

    # ── Row 1: extras ─────────────────────────────────────────────────────────

    @discord.ui.button(emoji="<:queue:1501403076148592650>", style=discord.ButtonStyle.secondary, row=1)  # 📋 Queue
    async def queue_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        result = await voice_manager.get_queue(self.guild)
        await interaction.response.send_message(result, ephemeral=True)

    @discord.ui.button(emoji="<:loop:1501401383142817973>", style=discord.ButtonStyle.secondary, row=1)  # 🔁 Loop
    async def loop_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        is_looping = await voice_manager.toggle_loop(self.guild)
        button.style = discord.ButtonStyle.primary if is_looping else discord.ButtonStyle.secondary
        await interaction.response.edit_message(view=self)

    @discord.ui.button(emoji="<:shuffle:1501401429741535345>", style=discord.ButtonStyle.secondary, row=1)  # 🔀 Shuffle
    async def shuffle_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        player = voice_manager.get_player(self.guild)
        if len(player.queue) < 2:
            await interaction.response.send_message("Not enough songs in queue to shuffle.", ephemeral=True)
            return
        await voice_manager.shuffle(self.guild)
        await interaction.response.send_message(f"🔀 Shuffled {len(player.queue)} songs.", ephemeral=True)

    @discord.ui.button(emoji="<:link:1501403040375242842>", style=discord.ButtonStyle.secondary, row=1)  # 🔗 Copy Link
    async def link_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        player = voice_manager.get_player(self.guild)
        if not player.current:
            await interaction.response.send_message("Nothing is playing.", ephemeral=True)
            return
        await interaction.response.send_message(player.current.webpage_url, ephemeral=True)


async def post_now_playing(
    channel: discord.TextChannel,
    player,
    *,
    title: str,
    artist: Optional[str],
    duration_seconds: Optional[int],
    queue_size: int,
    requested_by: str,
    thumbnail_url: Optional[str] = None,
    thumbnail_bytes: Optional[bytes] = None, 
) -> Optional["NowPlayingView"]:
    try:
        png_bytes = await generate_banner(title, artist, thumbnail_url, thumbnail_bytes)  # ← pass through
    except Exception as e:
        logger.error(f"[now_playing] banner generation failed: {e}")
        return None

    duration_str = f"0:00 / {_format_duration(duration_seconds)}"
    file = discord.File(fp=io.BytesIO(png_bytes), filename="now_playing.png")
    next_track = player.queue[0].title if player.queue else None
    embed = _build_playing_embed(
        queue_size=queue_size,
        requested_by=requested_by,
        duration_str=duration_str,
        next_track=next_track,
    )
    view = NowPlayingView(channel.guild, player)

    try:
        message = await channel.send(file=file, embed=embed, view=view)
    except Exception as e:
        logger.error(f"[now_playing] failed to post: {e}")
        return None

    view.message = message
    view.start_updates()
    player._now_playing_view = view
    player.now_playing_message = message

    return view


async def update_now_playing_queue(player, queue_size: int):
    msg = player.now_playing_message
    if not msg or not player.current:
        return

    try:
        track = player.current
        elapsed = player.elapsed_seconds
        duration_str = f"{_format_duration(int(elapsed))} / {_format_duration(track.duration)}"
        next_track = player.queue[0].title if player.queue else None
        embed = _build_playing_embed(
            queue_size=queue_size,
            requested_by=track.requested_by,
            duration_str=duration_str,
            next_track=next_track,
        )
        await msg.edit(embed=embed)
    except Exception as e:
        logger.error(f"[now_playing] failed to update queue count: {e}")
        player.now_playing_message = None